### ISSUE TITLE
 CASCI/SHCI solver pyscf example & extracting coefficients

### ISSUE THREAD

**Issue by jackweber1296** [QMC-Cornell/shci#78]
Hi,

I'm trying to set up arrow with pyscf, and am getting an error when trying to run the example below:

'''
Use Cornell SHCI program as the active space solver for CASSCF
'''

from pyscf import gto, scf, mcscf, cornell_shci

b = 1.2
mol = gto.M(
atom = 'H 0 0 0; H 0 0 %f'%b,
basis = 'cc-pvdz',
verbose = 4,
symmetry = 1
)
mf = scf.RHF(mol).run()

mc = mcscf.CASCI(mf, 4, 2)
mc.fcisolver = cornell_shci.SHCI(mol)
mc.kernel()
#Error:
ERROR: mpirun -n 1 /mnt/beegfs/home/friesner/jlw2245/shci/shci

CalledProcessError Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/pyscf/cornell_shci/shci.py in execute_shci(shciobj)
446 with open(output, 'w') as f:
--> 447 check_call(cmd.split(), cwd=shciobj.runtimedir, stdout=f, stderr=f)
448 except CalledProcessError as err:

/cm/local/apps/python3/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
362 cmd = popenargs[0]
--> 363 raise CalledProcessError(retcode, cmd)
364 return 0

CalledProcessError: Command '['mpirun', '-n', '1', '/mnt/beegfs/home/friesner/jlw2245/shci/shci']' returned non-zero exit status 139.

During handling of the above exception, another exception occurred:

TypeError Traceback (most recent call last)
in
----> 1 mc.kernel()

~/.local/lib/python3.7/site-packages/pyscf/mcscf/casci_symm.py in kernel(self, mo_coeff, ci0, verbose)
55 # Initialize/overwrite self.fcisolver.orbsym and self.fcisolver.wfnsym
56 mo_coeff = self.mo_coeff = label_symmetry_(self, mo_coeff, ci0)
---> 57 return casci.CASCI.kernel(self, mo_coeff, ci0, verbose)
58
59 def _eig(self, mat, b0, b1, orbsym=None):

~/.local/lib/python3.7/site-packages/pyscf/mcscf/casci.py in kernel(self, mo_coeff, ci0, verbose)
944
945 self.e_tot, self.e_cas, self.ci =
--> 946 kernel(self, mo_coeff, ci0=ci0, verbose=log)
947
948 if self.canonicalization:

~/.local/lib/python3.7/site-packages/pyscf/mcscf/casci.py in kernel(casci, mo_coeff, ci0, verbose, envs)
578 ci0=ci0, verbose=log,
579 max_memory=max_memory,
--> 580 ecore=energy_core)
581
582 t1 = log.timer('FCI solver', *t1)

~/.local/lib/python3.7/site-packages/pyscf/cornell_shci/shci.py in kernel(self, h1e, eri, norb, nelec, ci0, ecore, restart, **kwargs)
278 raise NotImplementedError
279
--> 280 execute_shci(self)
281 if self.verbose >= logger.DEBUG1:
282 with open(os.path.join(self.runtimedir, self.outputfile), 'r') as f:

~/.local/lib/python3.7/site-packages/pyscf/cornell_shci/shci.py in execute_shci(shciobj)
448 except CalledProcessError as err:
449 logger.error(shciobj, cmd)
--> 450 shciobj.stdout.write(check_output(['tail', '-100', output]))
451 raise err
452 return output

Is there anything more I need to do to get this working?

I was also wondering how exactly one would extract the CI coefficients and corresponding determinant structure - when using cornell_shci.SHCISCF to set up a CASSCF calculation it runs ok, but the .ci object is a float rather than an array of CI coefficients as I expected.

Thanks!
Jack

**Comment by ndattani** [comment]
Great to see this issue closed as completed. I'm curious what you changed to get it working?
