### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vvp-nsk** [QMC-Cornell/shci#79]
Hi!

Thank you so much for developing a robust and solid implementation of SHCI.  However, sometimes one might be interested in post-processing and analyzing of resulted MSD WF.  It would be of great help if you can provide a standalone tool that allows one to decode information written to the final 'wf_epsXXX.dat' binary file. In particular, would be great to extract in human-readable format:

- CI coefficients
- determinant's alpha and beta orbitals occupancy information

Thank you in advance!

With best regards, 
Victor

**Comment by CyrusUmrigar** [comment]
Tyler,

Do you have what Victor needs?

Cyrus

**Comment by tyanderson176** [comment]
Hi Victor,

I just added a new utility that prints out the CI coefficients. Just go to /tools/unpack_wf/, type 'make', and then type 'unpack_wf wf_epsXXX.dat' to print the unpacked wf to stdout. Please let me know if you have any issues.

**Comment by tyanderson176** [comment]
Hi Victor,

Thank you very much for pointing this out; I had forgotten to commit a small but important change to the way the *.dat files are generated. Please recompile SHCI with the change I just pushed and let me know if it works.

**Comment by vvp-nsk** [comment]
Dear Tyler,

Now everything works out.

Thank you very much for your assistance and effort!

With best regards, 
Victor
