### ISSUE TITLE
NaNs in PT sto

### ISSUE THREAD

**Issue by vvp-nsk** [QMC-Cornell/shci#81]
Hi!

I am suffering from a weird problem with computing stochastic PT2 energy correction.  With some eps_var thresholds, the PT2 energy corrections become NaN at the STO stage:

```
BEG OF #1, sto 1.00e-07 (state 0), eps_var=1.00e-04, perturbation[99.3/124.7]GB [0.481/0.000/361.767]s
Number of unique variational determinants in sample: 1,442,806
Batch id: 8 / 64
20% 40% 60% 80% 100%
Number of sto pt dets: 794,127,835
END OF create hc sums [118.4/143.8]GB [22.641/22.641/384.408]s
PT sto loop correction: -nan Ha
PT sto correction (eps1= 1.00e-04, eps_pt= 1.00e-07): -nan +- -nan Ha
PT sto total energy (eps1= 1.00e-04, eps_pt= 1.00e-07): -nan +- -nan Ha
Correlation energy (eps1= 1.00e-04, eps_pt= 1.00e-07): -nan +- -nan Ha
END OF #1, sto 1.00e-07 (state 0), eps_var=1.00e-04, perturbation[118.4/143.8]GB [15.592/38.197/399.963]s
```
The CI part always works fine but PT2 struggles. Do you have an idea on how to fix such instability problem?  To debug a problem, I can share the corresponding FCIDUMP and config.json files. 

Thank you in advance!

With best regards, 
Victor

**Comment by ndattani** [comment]
I guess including the FCIDUMP and `config.json` files would help others test whether or not the same NaN outputs are printed on other computers, or with other compilers.

**Comment by vvp-nsk** [comment]
Hi again!

Recompiling of Arrow with GCC and '-O2' optimization level does solve the issue. Probably, the Cray compiler with '-O3' does unsafe optimization. 

With best regards, 
Victor
